// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

/*
Package book is a generated protocol buffer package.

It is generated from these files:
	book.proto

It has these top-level messages:
	BookRequest
	BookResponse
*/
package book

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BookRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *BookRequest) Reset()                    { *m = BookRequest{} }
func (m *BookRequest) String() string            { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()               {}
func (*BookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BookResponse struct {
	Id     int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
}

func (m *BookResponse) Reset()                    { *m = BookResponse{} }
func (m *BookResponse) String() string            { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()               {}
func (*BookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BookResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*BookRequest)(nil), "book.BookRequest")
	proto.RegisterType((*BookResponse)(nil), "book.BookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Book service

type BookClient interface {
	Get(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookRequest, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) Get(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookRequest, error) {
	out := new(BookRequest)
	err := grpc.Invoke(ctx, "/book.Book/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Book service

type BookServer interface {
	Get(context.Context, *BookRequest) (*BookRequest, error)
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.Book/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).Get(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Book_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}

func init() { proto.RegisterFile("book.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x64, 0xd2, 0xf3, 0xf3, 0xd3,
	0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3,
	0xf3, 0x8a, 0x21, 0x6a, 0x94, 0x64, 0xb9, 0xb8, 0x9d, 0xf2, 0xf3, 0xb3, 0x83, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x98, 0x32, 0x53, 0x94, 0x7c, 0xb8, 0x78, 0x20, 0xd2, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xe8,
	0xf2, 0x42, 0x62, 0x5c, 0x6c, 0x89, 0xa5, 0x25, 0x19, 0xf9, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x50, 0x9e, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x66, 0x49, 0x4e, 0xaa, 0x04, 0x33, 0x58,
	0x18, 0xc2, 0x31, 0xf2, 0xe6, 0x62, 0x01, 0x99, 0x26, 0xe4, 0xcc, 0xc5, 0xec, 0x9e, 0x5a, 0x22,
	0x24, 0xa8, 0x07, 0x76, 0x2c, 0x92, 0xfd, 0x52, 0x98, 0x42, 0x4a, 0x62, 0x4d, 0x97, 0x9f, 0x4c,
	0x66, 0x12, 0x10, 0xe2, 0xd3, 0x2f, 0x33, 0xd4, 0x07, 0xc9, 0x16, 0xeb, 0x57, 0x67, 0xa6, 0xd4,
	0x26, 0xb1, 0x81, 0x3d, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x4d, 0x81, 0x5b, 0xf2,
	0x00, 0x00, 0x00,
}
